name: opencraft
version: 0.74-svn
summary: DOS emulator
description: |
  DOSBox is a x86 emulator with Tandy/Hercules/
  CGA/EGA/VGA/SVGA graphics sound and DOS. It's
  been designed to run old DOS games under
  platforms that don't support it.
confinement: devmode
base: core18
parts:
  opencraft:
    plugin: cmake
    source-type: tar
    source: https://github.com/lonyelon/Opencraft/archive/master.tar.gz
    build-packages:
      - g++
      - make
      - cmake
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libnoise-dev
apps:
  opencraft:
    command: opencraft
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'